/**
 * AIDisclosureBanner.tsx
 * ==========================================
 * EU AI ACT (Article 50) COMPLIANCE COMPONENT
 * 
 * Regulation 2024/1689, Article 50(1):
 * "Providers shall ensure that AI systems intended to interact directly
 *  with natural persons are designed and developed in such a way that
 *  the natural persons concerned are informed that they are interacting
 *  with an AI system."
 * 
 * This component must be placed on EVERY screen where the user
 * interacts with or receives output from the AI system:
 *  - Translation Trainer (scoring/feedback)
 *  - Writing Exercise (AI evaluation)
 *  - Grammar Practice (AI-powered feedback)
 *  - Grammar Quiz (AI question generation)
 *  - Discuss with Poly-Puff (AI chat)
 *  - Any results/feedback screen showing AI-generated content
 * 
 * Also satisfies:
 *  - Google AI Content Policy (generative AI disclosure)
 *  - Apple HIG for AI (transparency about AI capabilities)
 *  - China Generative AI Regulations (content labelling)
 *  - UAE AI Act 2026 (transparency requirements)
 * 
 * USAGE:
 *   import AIDisclosureBanner from '../components/AIDisclosureBanner';
 * 
 *   // At the top of any AI-powered screen, inside the ScrollView:
 *   <AIDisclosureBanner />
 * 
 *   // Or with a custom message:
 *   <AIDisclosureBanner message="Scores are generated by AI and may vary" />
 * 
 *   // Compact version for tight spaces:
 *   <AIDisclosureBanner compact />
 * 
 * FILE LOCATION: components/AIDisclosureBanner.tsx
 */

import React, { useState } from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
} from 'react-native';
import { Bot, X } from 'lucide-react-native';
import { useLanguage } from '../contexts/LanguageContext';

// English fallbacks — used when the current language pack hasn't translated
// the disclosure strings yet. Keep these in sync with translations.ts `en`.
const FALLBACK_COMPACT  = 'Powered by AI — responses may contain errors';
const FALLBACK_FULL     = 'This feature is powered by AI (OpenAI). Responses are generated automatically and may contain errors. Your grammar rules database is always the final authority.';
const FALLBACK_EXPAND   = 'AI-powered feature. Tap to see details.';
const FALLBACK_MINIMIZE = 'Minimize AI disclosure banner';

// ─── Poly-Puff Dark Theme ───
const C = {
  bg:         '#0A0E1A',
  card:       '#121829',
  cardAlt:    '#1A2137',
  text:       '#F0F4FF',
  textSec:    '#8B95B0',
  textMuted:  '#5A6380',
  border:     '#2A3352',
  cyan:       '#00E5FF',
  cyanDark:   '#003D47',
  amber:      '#FFBE0B',
};

interface AIDisclosureBannerProps {
  /** Custom message to display. Defaults to standard AI disclosure. */
  message?: string;
  /** Compact single-line version for tight layouts */
  compact?: boolean;
  /** Whether the banner can be dismissed (collapses to icon only) */
  dismissable?: boolean;
  /** Background color override */
  backgroundColor?: string;
}

export default function AIDisclosureBanner({
  message,
  compact = false,
  dismissable = true,
  backgroundColor,
}: AIDisclosureBannerProps) {
  const [dismissed, setDismissed] = useState(false);
  const { t } = useLanguage();

  const defaultMessage = t.aiDisclosureFull    || FALLBACK_FULL;
  const compactMessage = t.aiDisclosureCompact || FALLBACK_COMPACT;
  const expandLabel    = t.aiDisclosureExpand   || FALLBACK_EXPAND;
  const minimizeLabel  = t.aiDisclosureMinimize || FALLBACK_MINIMIZE;
  const displayMessage = message || (compact ? compactMessage : defaultMessage);

  // ─── Dismissed state: just show a small icon ───
  if (dismissed) {
    return (
      <TouchableOpacity
        style={s.dismissedPill}
        onPress={() => setDismissed(false)}
        activeOpacity={0.7}
        accessibilityLabel={expandLabel}
        accessibilityRole="button"
      >
        <Bot size={12} color={C.cyan} style={s.dismissedIcon} />
        <Text style={s.dismissedText}>AI</Text>
      </TouchableOpacity>
    );
  }

  // ─── Full banner ───
  return (
    <View
      style={[
        compact ? s.containerCompact : s.container,
        backgroundColor ? { backgroundColor } : null,
      ]}
      accessibilityLabel={`AI Disclosure: ${displayMessage}`}
      accessibilityRole="text"
    >
      <View style={s.contentRow}>
        <Bot size={compact ? 13 : 16} color={C.cyan} style={compact ? s.iconCompact : s.icon} />
        <Text style={compact ? s.textCompact : s.text}>
          {displayMessage}
        </Text>
        {dismissable && (
          <TouchableOpacity
            style={s.dismissBtn}
            onPress={() => setDismissed(true)}
            hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}
            accessibilityLabel={minimizeLabel}
            accessibilityRole="button"
          >
            <X size={14} color={C.textMuted} />
          </TouchableOpacity>
        )}
      </View>
    </View>
  );
}

// ═══════════════════════════════════════════
// STYLES
// ═══════════════════════════════════════════
const s = StyleSheet.create({
  // ── Full banner ──
  container: {
    backgroundColor: C.cyanDark + '25',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.cyan + '20',
    padding: 12,
    marginBottom: 16,
  },
  // ── Compact banner ──
  containerCompact: {
    backgroundColor: C.cyanDark + '20',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.cyan + '15',
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginBottom: 10,
  },
  contentRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  // ── Icon ──
  icon: {
    marginRight: 10,
    marginTop: 1,
  },
  iconCompact: {
    marginRight: 6,
    marginTop: 1,
  },
  // ── Text ──
  text: {
    flex: 1,
    fontSize: 12,
    color: C.cyan,
    lineHeight: 18,
    opacity: 0.85,
  },
  textCompact: {
    flex: 1,
    fontSize: 11,
    color: C.cyan,
    lineHeight: 16,
    opacity: 0.8,
  },
  // ── Dismiss button ──
  dismissBtn: {
    marginLeft: 8,
    paddingTop: 0,
  },
  // ── Dismissed pill ──
  dismissedPill: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: C.cyanDark + '20',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.cyan + '15',
    paddingVertical: 4,
    paddingHorizontal: 8,
    marginBottom: 10,
  },
  dismissedIcon: {
    marginRight: 4,
  },
  dismissedText: {
    fontSize: 10,
    color: C.cyan,
    fontWeight: '600',
    opacity: 0.7,
    letterSpacing: 0.5,
  },
});
