/**
 * TermsScreen.tsx
 *
 * WHERE THIS FILE GOES:
 *   D:\Project\MyProject\translation-trainer-frontend\app\TermsScreen.tsx
 *   (or wherever your existing TermsScreen.tsx lives — replace it entirely)
 *
 * WHAT CHANGED IN v3.0 vs v2.0:
 *   1. TERMS_VERSION bumped from '2.0' to '3.0'
 *      → Forces ALL existing users to re-accept on next app open
 *      → LegalGateController checks this value against AsyncStorage
 *
 *   2. Section 21 added: Plain-Language Summary (TL;DR) — moved to TOP
 *      → Required by UK Consumer Rights Act 2015 & EU Unfair Contract Terms Directive
 *
 *   3. Section 22 added: Cross-Border Data Transfer & SDAIA Sovereignty Disclosure
 *      → Required by Saudi SDAIA Personal Data Protection Law (PDPL) Art. 29-30
 *      → Also satisfies Egypt PDPL cross-border transfer disclosure requirement
 *      → Discloses transfer of data to OpenAI servers in the United States
 *
 *   4. Section 23 added: Pricing, VAT & Merchant of Record (SARS / South Africa)
 *      → Required by South African VAT Act (89/1991) & SARS e-commerce guidelines
 *      → Clarifies Google/Apple act as Merchant of Record for all transactions
 *      → States all prices include 15% South African VAT where applicable
 *
 *   5. Section 24 added: AI-Generated Content & Intellectual Property
 *      → References Ukraine sui generis 25-year protection for AI-generated works
 *      → Consistent with EU AI Act Art. 50 transparency obligations
 *      → Applies to all AI responses, translations, and feedback generated by Poly-Puff
 *
 *   6. One-Click Cancellation notice added to subscription section
 *      → Required by UK Digital Markets, Competition and Consumers Act 2024
 *      → Required by EU Omnibus Directive 2022 (effective across EU member states)
 */

import React, { useState, useRef } from 'react';
import {
  View,
  Text,
  Image,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  SafeAreaView,
  Linking,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import AsyncStorage from '@react-native-async-storage/async-storage';

// ─── Version constant ─────────────────────────────────────────────────────────
// IMPORTANT: Changing this value forces every existing user to re-read and
// re-accept the Terms on their next app open. Only bump it when content changes.
export const TERMS_VERSION = '3.0';

// ─── Types ────────────────────────────────────────────────────────────────────
interface SectionProps {
  number: string;
  title: string;
  children: React.ReactNode;
  highlight?: boolean; // true = amber left border (used for new/important sections)
}

interface TermsScreenProps {
  onAccept?: () => void;           // legacy — direct accept callback
  onComplete?: (status: string, ageGroup?: string) => void; // LegalGateController style
  onDecline?: () => void;
  ageGroup?: string;
}

// ─── Section component ────────────────────────────────────────────────────────
function Section({ number, title, children, highlight = false }: SectionProps) {
  const [expanded, setExpanded] = useState(false);

  return (
    <View style={[styles.section, highlight && styles.sectionHighlight]}>
      <TouchableOpacity
        style={styles.sectionHeader}
        onPress={() => setExpanded(!expanded)}
        accessibilityRole="button"
        accessibilityLabel={`${title}, section ${number}. Tap to ${expanded ? 'collapse' : 'expand'}`}
        accessibilityState={{ expanded }}
      >
        <View style={styles.sectionHeaderLeft}>
          <Text style={styles.sectionNumber}>{number}</Text>
          <Text style={styles.sectionTitle}>{title}</Text>
        </View>
        <Text style={styles.sectionChevron}>{expanded ? '▲' : '▼'}</Text>
      </TouchableOpacity>

      {expanded && (
        <View style={styles.sectionBody}>
          {children}
        </View>
      )}
    </View>
  );
}

// ─── Body text helpers ────────────────────────────────────────────────────────
function P({ children }: { children: React.ReactNode }) {
  return <Text style={styles.bodyText}>{children}</Text>;
}

function Bold({ children }: { children: React.ReactNode }) {
  return <Text style={styles.boldText}>{children}</Text>;
}

function Li({ children }: { children: React.ReactNode }) {
  return (
    <View style={styles.listItem}>
      <Text style={styles.bullet}>•</Text>
      <Text style={styles.listText}>{children}</Text>
    </View>
  );
}

// ─── Main screen ──────────────────────────────────────────────────────────────
export default function TermsScreen({ onAccept, onComplete, onDecline, ageGroup = 'adult' }: TermsScreenProps) {
  const scrollRef = useRef<ScrollView>(null);
  const [hasScrolledToBottom, setHasScrolledToBottom] = useState(false);
  const insets = useSafeAreaInsets();

  const handleScroll = (event: any) => {
    const { layoutMeasurement, contentOffset, contentSize } = event.nativeEvent;
    const isAtBottom =
      layoutMeasurement.height + contentOffset.y >= contentSize.height - 60;
    if (isAtBottom && !hasScrolledToBottom) {
      setHasScrolledToBottom(true);
    }
  };

  const handleAccept = async () => {
    try {
      await AsyncStorage.setItem('termsAccepted', 'true');
      await AsyncStorage.setItem('termsVersion', TERMS_VERSION);
      await AsyncStorage.setItem('termsAcceptedDate', new Date().toISOString());
    } catch (e) {
      console.error('TermsScreen: failed to save acceptance', e);
    }
    // Support both callback styles
    if (onComplete) {
      onComplete('done', ageGroup);
    } else if (onAccept) {
      onAccept();
    }
  };

  return (
    <SafeAreaView style={styles.container}>
      {/* Header */}
      <View style={[styles.header, { paddingTop: 16 + insets.top }]}>
        <Image
          source={require('../assets/images/logo-transparent.png')}
          style={{ width: 160, height: 36, resizeMode: 'contain', marginBottom: 8 }}
          accessibilityLabel="Poly-Puff"
        />
        <Text style={styles.headerTitle}>Terms & Conditions</Text>
        <Text style={styles.headerVersion}>Version {TERMS_VERSION} · March 2026</Text>
        <Text style={styles.headerSub}>
          Developed by Mark Middleton, Cape Town, South Africa
        </Text>
      </View>

      <ScrollView
        ref={scrollRef}
        style={styles.scroll}
        onScroll={handleScroll}
        scrollEventThrottle={16}
        showsVerticalScrollIndicator={true}
      >
        {/* ── NEW: Plain-Language TL;DR ──────────────────────────────────── */}
        <View style={styles.tldrBox}>
          <Text style={styles.tldrHeading}>Plain-Language Summary (TL;DR)</Text>
          <Text style={styles.tldrIntro}>
            These are your key rights and our key obligations — in plain English.
            The full legal text follows below.
          </Text>
          <Li>Poly-Puff uses AI to give you English grammar feedback. Responses are generated by OpenAI.</Li>
          <Li>Your data is processed on servers in the United States. We tell you this upfront.</Li>
          <Li>You can request account and data deletion at any time from Settings or poly-puff.com/delete-account.</Li>
          <Li>If you subscribe, you can cancel at any time in one step. No hidden steps or delays.</Li>
          <Li>Prices shown include VAT where applicable. Google and Apple handle all payments.</Li>
          <Li>AI-generated responses are labelled. They may contain errors — always verify important information.</Li>
          <Li>We do not sell your personal data to third parties.</Li>
          <Li>Users in the EU, UK, Saudi Arabia, Egypt, and South Africa have additional rights described below.</Li>
        </View>

        {/* ── Section 1: Acceptance ─────────────────────────────────────── */}
        <Section number="1" title="Acceptance of Terms">
          <P>
            By downloading, installing, or using Poly-Puff ("the App"), you agree to be bound
            by these Terms and Conditions ("Terms"). If you do not agree, do not use the App.
          </P>
          <P>
            These Terms were last updated on <Bold>1 March 2026</Bold> and supersede all
            previous versions. The current version is <Bold>{TERMS_VERSION}</Bold>.
          </P>
        </Section>

        {/* ── Section 2: Eligibility & Age ─────────────────────────────── */}
        <Section number="2" title="Eligibility & Age Requirements">
          <P>
            Minimum age requirements vary by region in accordance with applicable law:
          </P>
          <Li>Global default (COPPA / USA / Canada / UK): 13 years</Li>
          <Li>Egypt (PDPL Art. 2): 15 years</Li>
          <Li>European Union (GDPR Art. 8) and Vietnam: 16 years</Li>
          <Li>South Africa (POPIA), Saudi Arabia (SDAIA PDPL), UAE, India, Turkey: 18 years</Li>
          <P>
            Users below the applicable threshold require verifiable parental or guardian
            consent before registering or uploading a profile photo.
          </P>
        </Section>

        {/* ── Section 3: Description of Service ───────────────────────── */}
        <Section number="3" title="Description of Service">
          <P>
            Poly-Puff is an AI-powered English as a Second Language (ESL) learning application.
            The App provides translation training, grammar checking, vocabulary practice,
            listening exercises, and related educational features.
          </P>
          <P>
            Grammar feedback is generated using a combination of a structured rules database
            and the OpenAI API. AI-generated responses are clearly labelled within the App.
          </P>
        </Section>

        {/* ── Section 4: User Accounts ─────────────────────────────────── */}
        <Section number="4" title="User Accounts">
          <P>
            You are responsible for maintaining the confidentiality of your account credentials.
            You agree to notify us immediately of any unauthorised use of your account.
          </P>
          <P>
            We reserve the right to suspend or terminate accounts that violate these Terms,
            applicable law, or that are used for abusive, harmful, or fraudulent purposes.
          </P>
        </Section>

        {/* ── Section 5: Privacy & Data Collection ────────────────────── */}
        <Section number="5" title="Privacy & Data Collection">
          <P>
            Our Privacy Policy (version 3.0) is incorporated into these Terms by reference
            and governs how we collect, use, and protect your personal data.
          </P>
          <P>
            We collect only data necessary to provide the educational service, including
            your translation inputs, scores, and device locale. We do not sell your
            personal data to third parties.
          </P>
        </Section>

        {/* ── Section 6: AI Transparency (EU AI Act Art. 50) ───────────── */}
        <Section number="6" title="AI Transparency & EU AI Act Compliance">
          <P>
            Poly-Puff is classified as a <Bold>Limited Risk</Bold> AI system under the EU
            Artificial Intelligence Act (Regulation EU 2024/1689), which applies from
            2 August 2026 across all EU Member States.
          </P>
          <P>
            In accordance with Article 50 of the EU AI Act, we disclose that:
          </P>
          <Li>
            Grammar feedback and translation corrections are generated by an AI system
            (OpenAI GPT-series models).
          </Li>
          <Li>
            All AI-generated responses are labelled with an "AI" badge within the interface.
          </Li>
          <Li>
            AI responses may contain errors. They are intended as educational guidance,
            not authoritative linguistic rulings.
          </Li>
          <Li>
            You may report any AI response you believe is inaccurate or culturally
            insensitive using the Report button on any AI chat bubble.
          </Li>
        </Section>

        {/* ── Section 7: Acceptable Use ────────────────────────────────── */}
        <Section number="7" title="Acceptable Use">
          <P>You agree not to use the App to:</P>
          <Li>Submit content that is abusive, defamatory, or unlawful.</Li>
          <Li>Attempt to reverse-engineer, decompile, or extract the App's source code.</Li>
          <Li>Use the App for commercial purposes without our written consent.</Li>
          <Li>Circumvent age-verification or parental consent mechanisms.</Li>
          <Li>Transmit malware, spam, or other harmful content.</Li>
        </Section>

        {/* ── Section 8: Subscriptions & Payments ─────────────────────── */}
        <Section number="8" title="Subscriptions, Payments & Cancellation">
          <P>
            Premium features are available via in-app subscription purchased through
            Google Play or the Apple App Store.
          </P>
          <P>
            <Bold>One-click cancellation (UK & EU users):</Bold> In accordance with the
            UK Digital Markets, Competition and Consumers Act 2024 and the EU Omnibus
            Directive, you may cancel your subscription at any time in a single step
            through the subscription management screen in your device's app store settings.
            No additional steps, waiting periods, or retention flows will be imposed.
          </P>
          <P>
            Subscriptions automatically renew unless cancelled at least 24 hours before
            the end of the current billing period. You may manage or cancel your
            subscription at any time via your Google Play or Apple App Store account settings.
          </P>
          <P>
            Refunds are governed by the refund policies of Google Play and Apple App Store
            respectively, as they act as Merchant of Record for all transactions.
            See Section 23 for full pricing and VAT details.
          </P>
        </Section>

        {/* ── Section 9: Children & Parental Consent ───────────────────── */}
        <Section number="9" title="Children's Privacy & Parental Consent">
          <P>
            We take the protection of children's data seriously. Where a user is below
            the applicable regional age threshold, a parent or legal guardian must complete
            a verification challenge before the child may register or upload a profile photo.
          </P>
          <P>
            For users in Egypt aged under 15, explicit written guardian consent is required
            in accordance with Egypt PDPL Executive Regulations (Decree No. 816 of 2025).
            Consent mechanisms for children's data are subject to approval by the Egyptian
            Personal Data Protection Center.
          </P>
          <P>
            We do not knowingly collect data beyond what is strictly necessary for the
            educational service from users under the applicable age threshold.
          </P>
        </Section>

        {/* ── Section 10: Intellectual Property (App) ──────────────────── */}
        <Section number="10" title="Intellectual Property — App Content">
          <P>
            All content within the App, including but not limited to lesson content,
            graphics, audio, and the grammar rules database, is owned by or licensed to
            Poly-Puff and is protected by applicable copyright and intellectual property laws.
          </P>
          <P>
            Grammar rules data is derived in part from VOA Learning English public domain
            materials. All other content is proprietary.
          </P>
        </Section>

        {/* ── Section 11: User-Generated Content ───────────────────────── */}
        <Section number="11" title="User-Generated Content">
          <P>
            Translation inputs and practice submissions you provide remain your property.
            By submitting content to the App, you grant us a limited, non-exclusive,
            royalty-free licence to process that content solely for the purpose of
            providing and improving the educational service.
          </P>
          <P>
            We do not use your personal translation inputs to train AI models without
            your separate, explicit consent.
          </P>
        </Section>

        {/* ── Section 12: Disclaimers ───────────────────────────────────── */}
        <Section number="12" title="Disclaimers & Limitation of Liability">
          <P>
            The App is provided "as is" without warranties of any kind, express or implied.
            We do not warrant that the App will be error-free, uninterrupted, or suitable
            for any particular educational purpose.
          </P>
          <P>
            To the maximum extent permitted by applicable law, we shall not be liable for
            any indirect, incidental, or consequential damages arising from your use of
            the App.
          </P>
          <P>
            Nothing in these Terms excludes or limits liability for death or personal injury
            caused by negligence, or for fraud or fraudulent misrepresentation.
          </P>
        </Section>

        {/* ── Section 13: Governing Law ────────────────────────────────── */}
        <Section number="13" title="Governing Law & Jurisdiction">
          <P>
            These Terms are governed by the laws of the Republic of South Africa.
            Any disputes shall be subject to the non-exclusive jurisdiction of the courts
            of South Africa.
          </P>
          <P>
            Users in the European Union retain the right to bring claims before the courts
            of their country of residence in accordance with applicable EU consumer law.
            Users in the United Kingdom retain equivalent rights under UK consumer protection law.
          </P>
        </Section>

        {/* ── Section 14: Termination ───────────────────────────────────── */}
        <Section number="14" title="Termination & Account Deletion">
          <P>
            You may request deletion of your account and associated data at any time via
            Settings → Delete Account within the App, which opens our deletion page, or by submitting a request at{' '}
            <Text
              style={styles.link}
              onPress={() => Linking.openURL('https://poly-puff.com/delete-account')}
              accessibilityRole="link"
              accessibilityLabel="Visit poly-puff.com/delete-account to request account deletion"
            >
              poly-puff.com/delete-account
            </Text>
            .
          </P>
          <P>
            Upon a verified deletion request, all personal data associated with your account will be
            permanently erased within 30 days, except where retention is required by law
            (e.g., financial records for tax compliance purposes).
          </P>
        </Section>

        {/* ── Section 15: Changes to Terms ─────────────────────────────── */}
        <Section number="15" title="Changes to These Terms">
          <P>
            We may update these Terms from time to time. When we make material changes,
            we will increment the version number and require you to re-accept the updated
            Terms before continuing to use the App.
          </P>
          <P>
            Continued use of the App after accepting updated Terms constitutes agreement
            to the revised Terms.
          </P>
        </Section>

        {/* ── Section 16: Contact ───────────────────────────────────────── */}
        <Section number="16" title="Contact & Complaints">
          <P>
            For questions, complaints, or data subject requests, contact us at:
          </P>
          <P>
            <Bold>Email:</Bold> mark.david.middleton@gmail.com{'\n'}
            <Bold>App:</Bold> poly-puff.com{'\n'}
            <Bold>Delete account:</Bold> poly-puff.com/delete-account
          </P>
          <P>
            EU users may also lodge complaints with their national data protection authority.
            UK users may contact the Information Commissioner's Office (ICO).
            South African users may contact the Information Regulator.
          </P>
        </Section>

        {/* ── Section 17: GDPR Rights (EU/UK) ─────────────────────────── */}
        <Section number="17" title="GDPR & UK GDPR — EU & UK User Rights">
          <P>
            If you are located in the European Union or United Kingdom, you have the
            following rights under GDPR / UK GDPR:
          </P>
          <Li>Right of access — request a copy of your personal data.</Li>
          <Li>Right to rectification — correct inaccurate data.</Li>
          <Li>Right to erasure ("right to be forgotten").</Li>
          <Li>Right to restriction of processing.</Li>
          <Li>Right to data portability.</Li>
          <Li>Right to object to processing based on legitimate interests.</Li>
          <Li>Right not to be subject to solely automated decision-making with legal effects.</Li>
          <P>
            To exercise any of these rights, contact us at mark.david.middleton@gmail.com
            or via poly-puff.com/delete-account.
          </P>
        </Section>

        {/* ── Section 18: POPIA Rights (South Africa) ──────────────────── */}
        <Section number="18" title="POPIA — South African User Rights">
          <P>
            If you are located in South Africa, you have the following rights under the
            Protection of Personal Information Act 4 of 2013 (POPIA):
          </P>
          <Li>Right to be notified of collection of personal information.</Li>
          <Li>Right of access to your personal information.</Li>
          <Li>Right to request correction or deletion of personal information.</Li>
          <Li>Right to object to the processing of your personal information.</Li>
          <Li>Right to submit a complaint to the Information Regulator.</Li>
          <P>
            The minimum age of consent for data processing in South Africa is 18 years.
            Processing of personal information of persons under 18 requires guardian consent.
          </P>
        </Section>

        {/* ── Section 19: COPPA (USA) ───────────────────────────────────── */}
        <Section number="19" title="COPPA — United States User Rights">
          <P>
            We comply with the Children's Online Privacy Protection Act (COPPA).
            We do not knowingly collect personal information from children under 13
            in the United States without verifiable parental consent.
          </P>
          <P>
            Parents may review, correct, or request deletion of their child's data
            by contacting mark.david.middleton@gmail.com.
          </P>
        </Section>

        {/* ── Section 20: LGPD (Brazil) ────────────────────────────────── */}
        <Section number="20" title="LGPD — Brazilian User Rights">
          <P>
            If you are located in Brazil, you have the following rights under the Lei Geral
            de Proteção de Dados (LGPD, Law No. 13,709/2018):
          </P>
          <Li>Confirmation of the existence of processing.</Li>
          <Li>Access to your personal data.</Li>
          <Li>Correction of incomplete, inaccurate, or outdated data.</Li>
          <Li>Anonymisation, blocking, or deletion of unnecessary or excessive data.</Li>
          <Li>Portability of your data to another service provider.</Li>
          <Li>Information about entities with whom data has been shared.</Li>
          <Li>Right to revoke consent at any time.</Li>
          <P>
            The minimum age for data processing consent in Brazil is 12 years.
            Data processing for users aged 12–17 requires parental authorisation.
          </P>
        </Section>

        {/* ═══════════════════════════════════════════════════════════════════
            NEW SECTIONS ADDED IN v3.0
        ════════════════════════════════════════════════════════════════════ */}

        {/* ── Section 21: Cross-Border Data Transfer & SDAIA ───────────── */}
        <Section number="21" title="Cross-Border Data Transfers & Sovereign Data Disclosure" highlight>
          <P>
            <Bold>This section is required by Saudi SDAIA PDPL (Arts. 29–30),
            Egypt PDPL (Executive Regulations, Decree 816/2025), and GDPR Chapter V.</Bold>
          </P>
          <P>
            To provide AI-powered grammar feedback, your translation inputs are transmitted
            to OpenAI, LLC, whose servers are located in the <Bold>United States of America</Bold>.
            This constitutes a cross-border transfer of personal data outside your country
            of residence.
          </P>
          <P>
            By using Poly-Puff's AI features, you explicitly consent to this transfer
            as required by applicable law in your jurisdiction, including:
          </P>
          <Li>
            <Bold>Saudi Arabia (SDAIA PDPL):</Bold> Data is transferred to the United States
            under your explicit consent and for the purpose of fulfilling the educational
            service contract. We confirm that appropriate contractual safeguards are in
            place via OpenAI's Data Processing Agreement. Saudi users' data sovereignty
            rights are acknowledged and respected — we do not store your data on Saudi
            servers, and this is disclosed transparently as required.
          </Li>
          <Li>
            <Bold>Egypt (PDPL):</Bold> Cross-border transfer to OpenAI US servers occurs
            under your explicit consent and to fulfil the service. We take precautions
            to ensure an equivalent level of legal and technical protection in line with
            Egypt PDPL Executive Regulations.
          </Li>
          <Li>
            <Bold>EU / UK (GDPR / UK GDPR):</Bold> Transfers to OpenAI are governed by
            Standard Contractual Clauses (SCCs) as approved by the European Commission.
          </Li>
          <Li>
            <Bold>All other regions:</Bold> Transfer is made on the basis of your consent
            and the necessity of the transfer to perform the service you have requested.
          </Li>
          <P>
            <Bold>What data is transferred:</Bold> Only your translation input text and
            your app locale (language setting) are sent to OpenAI for grammar analysis.
            No names, email addresses, or device identifiers are transmitted to OpenAI.
          </P>
          <P>
            <Bold>OpenAI's data practices</Bold> are governed by OpenAI's Terms of Use
            and Privacy Policy, available at{' '}
            <Text
              style={styles.link}
              onPress={() => Linking.openURL('https://openai.com/en-GB/policies/terms-of-use/')}
              accessibilityRole="link"
              accessibilityLabel="Open OpenAI Terms of Use in your browser"
            >
              openai.com/policies/terms-of-use
            </Text>
            .
          </P>
        </Section>

        {/* ── Section 22: Pricing, VAT & Merchant of Record ────────────── */}
        <Section number="22" title="Pricing, VAT & Merchant of Record (SARS)" highlight>
          <P>
            <Bold>This section satisfies SARS (South African Revenue Service) e-commerce
            VAT disclosure requirements and the VAT Act 89 of 1991.</Bold>
          </P>
          <P>
            All in-app purchases and subscription fees are processed exclusively through
            Google Play (Google LLC) or the Apple App Store (Apple Inc.), who act as the
            <Bold> Merchant of Record</Bold> for all transactions. This means:
          </P>
          <Li>
            Google and Apple collect payment, issue receipts, and are responsible for
            VAT/GST remittance in each jurisdiction they operate in.
          </Li>
          <Li>
            For South African users, <Bold>prices displayed in the Google Play Store or
            Apple App Store include 15% VAT</Bold> as required by the South African
            VAT Act 89 of 1991.
          </Li>
          <Li>
            Poly-Puff (Mark Middleton) is registered under the Small Business Programme
            and does not independently collect or remit VAT — this is handled entirely
            by Google and Apple as Merchants of Record.
          </Li>
          <Li>
            For refund requests, contact Google Play or Apple App Store support directly,
            as they are the contracting party for your purchase.
          </Li>
          <P>
            Pricing is displayed in your local currency where available.
            Final pricing is set by the respective app store platform and may differ
            from regional list prices due to exchange rate fluctuations and platform fees.
          </P>
        </Section>

        {/* ── Section 23: AI-Generated Content & IP ────────────────────── */}
        <Section number="23" title="AI-Generated Content & Intellectual Property" highlight>
          <P>
            <Bold>This section addresses the IP status of AI-generated responses
            consistent with the EU AI Act Art. 50 and international IP developments.</Bold>
          </P>
          <P>
            All grammar feedback, translation corrections, and educational content
            generated by Poly-Puff's AI systems are produced by OpenAI's language models
            and are considered <Bold>AI-generated outputs</Bold>.
          </P>
          <P>
            <Bold>Ownership and sui generis protection:</Bold>
          </P>
          <Li>
            Under most jurisdictions, AI-generated content without human authorship
            does not qualify for traditional copyright protection. You are free to use
            AI-generated feedback for personal educational purposes.
          </Li>
          <Li>
            In Ukraine, AI-generated works may be protected by a <Bold>25-year sui generis
            right</Bold> under Ukrainian IP law. To the extent this protection applies to
            outputs generated by Poly-Puff, such rights are held by Poly-Puff / Mark Middleton.
          </Li>
          <Li>
            You may not reproduce, redistribute, or commercialise AI-generated responses
            from Poly-Puff without prior written permission.
          </Li>
          <P>
            <Bold>Accuracy disclaimer:</Bold> AI-generated grammar feedback is for
            educational purposes only. It may contain errors, cultural assumptions,
            or regional variations. Always consult a qualified language teacher for
            formal assessments or high-stakes language decisions.
          </P>
          <P>
            All AI responses within the App are labelled with an <Bold>"AI" badge</Bold>
            and displayed on a distinct background in compliance with Apple Human Interface
            Guidelines for AI-generated content and EU AI Act Article 50 transparency
            obligations.
          </P>
          <P>
            <Bold>Speech Recognition Limitations:</Bold> The voice input feature in the
            Translation Trainer uses Google's on-device speech recognition engine. This
            engine does not fully support all 41 native languages in Poly-Puff. Voice input
            is unavailable in the Translation Trainer for speakers of: Igbo, Hausa, Zulu,
            Yoruba, Amharic, Swahili, Urdu, Punjabi, Gujarati, Marathi, Tamil, Nepali,
            Sinhala, and Persian. Affected users are notified at the point of language
            selection in their profile. Voice input remains available to all users in the
            Placement Test. This limitation does not affect any other app features.
          </P>
        </Section>

        {/* ── Section 24: Egypt PDPL Specific ──────────────────────────── */}
        <Section number="24" title="Egypt PDPL — Egyptian User Rights">
          <P>
            If you are located in Egypt, you have rights under the Personal Data Protection
            Law No. 151 of 2020 (PDPL) and its Executive Regulations (Decree 816/2025),
            which come into full force on <Bold>1 November 2026</Bold>.
          </P>
          <Li>Right to be informed about the collection and use of your data.</Li>
          <Li>Right of access to your personal data.</Li>
          <Li>Right to correct inaccurate personal data.</Li>
          <Li>Right to request deletion of your personal data.</Li>
          <Li>Right to withdraw consent at any time.</Li>
          <Li>Right to lodge a complaint with the Personal Data Protection Center (PDPC).</Li>
          <P>
            <Bold>Children's data (Egypt):</Bold> The PDPL classifies children's data as
            sensitive personal data. Explicit written consent from a legal guardian is
            required before processing personal data of users under 15 years of age.
            Users aged 15–18 may consent independently or through a guardian.
          </P>
          <P>
            Cross-border data transfers affecting Egyptian users require your explicit
            consent and compliance with PDPL transfer controls. See Section 21 for details.
          </P>
        </Section>

        {/* Bottom padding */}
        <View style={{ height: 32 }} />
      </ScrollView>

      {/* Accept / Decline buttons */}
      <View style={[styles.footer, { paddingBottom: 16 + insets.bottom }]}>
        {!hasScrolledToBottom && (
          <Text style={styles.scrollHint}>
            Please scroll to the bottom to review all terms before accepting.
          </Text>
        )}

        <TouchableOpacity
          style={[styles.acceptButton, !hasScrolledToBottom && styles.acceptButtonDisabled]}
          onPress={hasScrolledToBottom ? handleAccept : undefined}
          disabled={!hasScrolledToBottom}
          accessibilityRole="button"
          accessibilityLabel="Accept Terms and Conditions"
          accessibilityState={{ disabled: !hasScrolledToBottom }}
        >
          <Text style={styles.acceptButtonText}>
            I Accept — Version {TERMS_VERSION}
          </Text>
        </TouchableOpacity>

        {onDecline && (
          <TouchableOpacity
            style={styles.declineButton}
            onPress={onDecline}
            accessibilityRole="button"
            accessibilityLabel="Decline Terms and Conditions"
          >
            <Text style={styles.declineButtonText}>Decline</Text>
          </TouchableOpacity>
        )}
      </View>
    </SafeAreaView>
  );
}

// ─── Styles ───────────────────────────────────────────────────────────────────
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0A0A0F',
  },
  header: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#1E1E2E',
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 2,
  },
  headerVersion: {
    fontSize: 13,
    color: '#7EC8E3',
    marginBottom: 2,
  },
  headerSub: {
    fontSize: 11,
    color: '#6B7280',
  },
  scroll: {
    flex: 1,
    paddingHorizontal: 16,
  },

  // TL;DR box
  tldrBox: {
    backgroundColor: '#0F1F2E',
    borderWidth: 1,
    borderColor: '#7EC8E3',
    borderRadius: 12,
    padding: 16,
    marginTop: 16,
    marginBottom: 8,
  },
  tldrHeading: {
    fontSize: 15,
    fontWeight: '700',
    color: '#7EC8E3',
    marginBottom: 6,
  },
  tldrIntro: {
    fontSize: 13,
    color: '#9CA3AF',
    marginBottom: 10,
    lineHeight: 18,
  },

  // Sections
  section: {
    backgroundColor: '#111118',
    borderRadius: 10,
    marginBottom: 8,
    overflow: 'hidden',
    borderWidth: 0.5,
    borderColor: '#1E1E2E',
  },
  sectionHighlight: {
    borderLeftWidth: 3,
    borderLeftColor: '#F59E0B',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 14,
  },
  sectionHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 10,
  },
  sectionNumber: {
    fontSize: 11,
    fontWeight: '600',
    color: '#7EC8E3',
    minWidth: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#E5E7EB',
    flex: 1,
  },
  sectionChevron: {
    fontSize: 10,
    color: '#6B7280',
    marginLeft: 8,
  },
  sectionBody: {
    paddingHorizontal: 16,
    paddingBottom: 14,
    borderTopWidth: 0.5,
    borderTopColor: '#1E1E2E',
    paddingTop: 12,
  },

  // Typography
  bodyText: {
    fontSize: 13,
    color: '#9CA3AF',
    lineHeight: 20,
    marginBottom: 8,
  },
  boldText: {
    fontWeight: '700',
    color: '#D1D5DB',
  },
  link: {
    color: '#7EC8E3',
    textDecorationLine: 'underline',
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 6,
    paddingLeft: 4,
  },
  bullet: {
    fontSize: 13,
    color: '#7EC8E3',
    marginRight: 8,
    marginTop: 1,
  },
  listText: {
    fontSize: 13,
    color: '#9CA3AF',
    lineHeight: 20,
    flex: 1,
  },

  // Footer
  footer: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#1E1E2E',
    backgroundColor: '#0A0A0F',
  },
  scrollHint: {
    fontSize: 12,
    color: '#F59E0B',
    textAlign: 'center',
    marginBottom: 8,
  },
  acceptButton: {
    backgroundColor: '#7EC8E3',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    marginBottom: 8,
  },
  acceptButtonDisabled: {
    backgroundColor: '#1E2D3A',
  },
  acceptButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0A0A0F',
  },
  declineButton: {
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#374151',
  },
  declineButtonText: {
    fontSize: 14,
    color: '#6B7280',
  },
});
